### ISSUE TITLE
Duplicate label

### ISSUE THREAD

**Issue by darkdragon-001** [KITrobotics/Latex_Template#13]
Since you copied the table from `6-Results.tex` to `4-Concept.tex` in 16082b76daf709fba4214fb0fb67a5bdaff5e18b, now the same label is defined twice ([4-Concept.tex:25](https://github.com/KITrobotics/Latex_Template/blob/16082b76daf709fba4214fb0fb67a5bdaff5e18b/Content/4-Concept.tex#L25))

**Comment by destogl** [comment]
in the current version is this repaired.
