### ISSUE TITLE
Numbering of Pages: Use roman before start of actual content

### ISSUE THREAD

**Issue by wirthual** [KITrobotics/Latex_Template#16]
Suggestion:

In my opinion the numbering before the toc should be in roman numbers, since in the actual version page number 9 exists 2 times
![latex_toc_arabic](https://user-images.githubusercontent.com/2640499/50696983-36cf8880-1041-11e9-8ad5-8e8e587ddd96.png)

I changed it by adding `\pagenumbering{roman}` to the very begining of the thesis.tex after `\setpdf`. Not sure this is the right place, however for me this seems the right option.

In my version the table of content now looks like this
![latex_toc_roman](https://user-images.githubusercontent.com/2640499/50697077-831ac880-1041-11e9-8d56-b33173ffe27a.png)

(One image in english, one in german. Sorry for that.)

**Comment by destogl** [comment]
solved in #17
