### ISSUE TITLE
Wrong header in Appendix

### ISSUE THREAD

**Issue by wirthual** [KITrobotics/Latex_Template#21]
Odd page numbers correct:
![image](https://user-images.githubusercontent.com/2640499/58210526-e86a1000-7ce9-11e9-9080-35218b7e426a.png)
 
However, even page numbers:
![image](https://user-images.githubusercontent.com/2640499/58210583-1e0ef900-7cea-11e9-8b4e-009500f33483.png)

**Comment by destogl** [comment]
What is missing. I believe that for even pages there is name of chapter used and for odd pages name of a section.... could it be?

how should it look like in your opinion?

**Comment by wirthual** [comment]
Nothing is missing, however the chapter title should not be Bibliography but Appendix instead. Odd pages seem correct.

Should be consinstent with the previous headers.

**Comment by destogl** [comment]
Aha OK.

Puh, hard to say. You should look if there is chapter appendinx setted. I have to also to search for it. Try first by yourself. It should not be to hard.

**Comment by destogl** [comment]
@wirthual: did you find anything?

**Comment by wirthual** [comment]
Couldn't figure out why exactly this happens, so I decided to remove the header text on even and odd pages for the Appendix section by adding:
```
\pagestyle{scrheadings}
\clearscrheadfoot
```
 Just after the beginning of the chapter

**Comment by destogl** [comment]
Should be solved.
